//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Печать ФОТО.
    /// </summary>
    // *** Start programmer edit section *** (ПечатьФОТО CustomAttributes)

    // *** End programmer edit section *** (ПечатьФОТО CustomAttributes)
    [AutoAltered()]
    [Caption("Печать ФОТО")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПечатьФОТОE", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "СпособОплаты as \'Способ оплаты\'"})]
    [AssociatedDetailViewAttribute("ПечатьФОТОE", "Фото", "ФотоE", true, "", "Фото", true, new string[] {
            ""})]
    [View("ПечатьФОТОL", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "СпособОплаты as \'Способ оплаты\'"})]
    public class ПечатьФОТО : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаСоздания = System.DateTime.Now;
        
        private IIS.Fotokiosk2.ТипОплаты fСпособОплаты;
        
        private IIS.Fotokiosk2.DetailArrayOfФото fФото;
        
        // *** Start programmer edit section *** (ПечатьФОТО CustomMembers)

        // *** End programmer edit section *** (ПечатьФОТО CustomMembers)

        
        /// <summary>
        /// ДатаСоздания.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФОТО.ДатаСоздания CustomAttributes)

        // *** End programmer edit section *** (ПечатьФОТО.ДатаСоздания CustomAttributes)
        public virtual System.DateTime ДатаСоздания
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФОТО.ДатаСоздания Get start)

                // *** End programmer edit section *** (ПечатьФОТО.ДатаСоздания Get start)
                System.DateTime result = this.fДатаСоздания;
                // *** Start programmer edit section *** (ПечатьФОТО.ДатаСоздания Get end)

                // *** End programmer edit section *** (ПечатьФОТО.ДатаСоздания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФОТО.ДатаСоздания Set start)

                // *** End programmer edit section *** (ПечатьФОТО.ДатаСоздания Set start)
                this.fДатаСоздания = value;
                // *** Start programmer edit section *** (ПечатьФОТО.ДатаСоздания Set end)

                // *** End programmer edit section *** (ПечатьФОТО.ДатаСоздания Set end)
            }
        }
        
        /// <summary>
        /// СпособОплаты.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФОТО.СпособОплаты CustomAttributes)

        // *** End programmer edit section *** (ПечатьФОТО.СпособОплаты CustomAttributes)
        public virtual IIS.Fotokiosk2.ТипОплаты СпособОплаты
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФОТО.СпособОплаты Get start)

                // *** End programmer edit section *** (ПечатьФОТО.СпособОплаты Get start)
                IIS.Fotokiosk2.ТипОплаты result = this.fСпособОплаты;
                // *** Start programmer edit section *** (ПечатьФОТО.СпособОплаты Get end)

                // *** End programmer edit section *** (ПечатьФОТО.СпособОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФОТО.СпособОплаты Set start)

                // *** End programmer edit section *** (ПечатьФОТО.СпособОплаты Set start)
                this.fСпособОплаты = value;
                // *** Start programmer edit section *** (ПечатьФОТО.СпособОплаты Set end)

                // *** End programmer edit section *** (ПечатьФОТО.СпособОплаты Set end)
            }
        }
        
        /// <summary>
        /// Печать ФОТО.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФОТО.Фото CustomAttributes)

        // *** End programmer edit section *** (ПечатьФОТО.Фото CustomAttributes)
        public virtual IIS.Fotokiosk2.DetailArrayOfФото Фото
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФОТО.Фото Get start)

                // *** End programmer edit section *** (ПечатьФОТО.Фото Get start)
                if ((this.fФото == null))
                {
                    this.fФото = new IIS.Fotokiosk2.DetailArrayOfФото(this);
                }
                IIS.Fotokiosk2.DetailArrayOfФото result = this.fФото;
                // *** Start programmer edit section *** (ПечатьФОТО.Фото Get end)

                // *** End programmer edit section *** (ПечатьФОТО.Фото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФОТО.Фото Set start)

                // *** End programmer edit section *** (ПечатьФОТО.Фото Set start)
                this.fФото = value;
                // *** Start programmer edit section *** (ПечатьФОТО.Фото Set end)

                // *** End programmer edit section *** (ПечатьФОТО.Фото Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПечатьФОТОE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьФОТОE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьФОТОE", typeof(IIS.Fotokiosk2.ПечатьФОТО));
                }
            }
            
            /// <summary>
            /// "ПечатьФОТОL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьФОТОL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьФОТОL", typeof(IIS.Fotokiosk2.ПечатьФОТО));
                }
            }
        }
    }
}
