//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Фото.
    /// </summary>
    // *** Start programmer edit section *** (Фото CustomAttributes)

    // *** End programmer edit section *** (Фото CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФотоE", new string[] {
            "Услуги as \'Услуги\'",
            "Услуги.Наименование as \'Наименование\'",
            "Количество as \'Количество\'",
            "Бумага as \'Бумага\'",
            "Услуги.Цена as \'Цена\'"}, Hidden=new string[] {
            "Услуги.Наименование"})]
    [MasterViewDefineAttribute("ФотоE", "Услуги", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class Фото : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Fotokiosk2.ТипБумаги fБумага;
        
        private IIS.Fotokiosk2.Услуги fУслуги;
        
        private IIS.Fotokiosk2.ПечатьФОТО fПечатьФОТО;
        
        // *** Start programmer edit section *** (Фото CustomMembers)

        // *** End programmer edit section *** (Фото CustomMembers)

        
        /// <summary>
        /// Бумага.
        /// </summary>
        // *** Start programmer edit section *** (Фото.Бумага CustomAttributes)

        // *** End programmer edit section *** (Фото.Бумага CustomAttributes)
        public virtual IIS.Fotokiosk2.ТипБумаги Бумага
        {
            get
            {
                // *** Start programmer edit section *** (Фото.Бумага Get start)

                // *** End programmer edit section *** (Фото.Бумага Get start)
                IIS.Fotokiosk2.ТипБумаги result = this.fБумага;
                // *** Start programmer edit section *** (Фото.Бумага Get end)

                // *** End programmer edit section *** (Фото.Бумага Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.Бумага Set start)

                // *** End programmer edit section *** (Фото.Бумага Set start)
                this.fБумага = value;
                // *** Start programmer edit section *** (Фото.Бумага Set end)

                // *** End programmer edit section *** (Фото.Бумага Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Фото.Количество CustomAttributes)

        // *** End programmer edit section *** (Фото.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Фото.Количество Get start)

                // *** End programmer edit section *** (Фото.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Фото.Количество Get end)

                // *** End programmer edit section *** (Фото.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.Количество Set start)

                // *** End programmer edit section *** (Фото.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Фото.Количество Set end)

                // *** End programmer edit section *** (Фото.Количество Set end)
            }
        }
        
        /// <summary>
        /// Фото.
        /// </summary>
        // *** Start programmer edit section *** (Фото.Услуги CustomAttributes)

        // *** End programmer edit section *** (Фото.Услуги CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуги"})]
        [NotNull()]
        public virtual IIS.Fotokiosk2.Услуги Услуги
        {
            get
            {
                // *** Start programmer edit section *** (Фото.Услуги Get start)

                // *** End programmer edit section *** (Фото.Услуги Get start)
                IIS.Fotokiosk2.Услуги result = this.fУслуги;
                // *** Start programmer edit section *** (Фото.Услуги Get end)

                // *** End programmer edit section *** (Фото.Услуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.Услуги Set start)

                // *** End programmer edit section *** (Фото.Услуги Set start)
                this.fУслуги = value;
                // *** Start programmer edit section *** (Фото.Услуги Set end)

                // *** End programmer edit section *** (Фото.Услуги Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Fotokiosk2.ПечатьФОТО.
        /// </summary>
        // *** Start programmer edit section *** (Фото.ПечатьФОТО CustomAttributes)

        // *** End programmer edit section *** (Фото.ПечатьФОТО CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПечатьФОТО"})]
        public virtual IIS.Fotokiosk2.ПечатьФОТО ПечатьФОТО
        {
            get
            {
                // *** Start programmer edit section *** (Фото.ПечатьФОТО Get start)

                // *** End programmer edit section *** (Фото.ПечатьФОТО Get start)
                IIS.Fotokiosk2.ПечатьФОТО result = this.fПечатьФОТО;
                // *** Start programmer edit section *** (Фото.ПечатьФОТО Get end)

                // *** End programmer edit section *** (Фото.ПечатьФОТО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.ПечатьФОТО Set start)

                // *** End programmer edit section *** (Фото.ПечатьФОТО Set start)
                this.fПечатьФОТО = value;
                // *** Start programmer edit section *** (Фото.ПечатьФОТО Set end)

                // *** End programmer edit section *** (Фото.ПечатьФОТО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФотоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФотоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФотоE", typeof(IIS.Fotokiosk2.Фото));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Фото.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfФото CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfФото CustomAttributes)
    public class DetailArrayOfФото : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Fotokiosk2.DetailArrayOfФото members)

        // *** End programmer edit section *** (IIS.Fotokiosk2.DetailArrayOfФото members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Фото by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Фото.
        /// </summary>
        public DetailArrayOfФото(IIS.Fotokiosk2.ПечатьФОТО fПечатьФОТО) : 
                base(typeof(Фото), ((ICSSoft.STORMNET.DataObject)(fПечатьФОТО)))
        {
        }
        
        public IIS.Fotokiosk2.Фото this[int index]
        {
            get
            {
                return ((IIS.Fotokiosk2.Фото)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Fotokiosk2.Фото dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
